import Banner from "@/components/banner";
import Head from "next/head";
import React from "react";
import styles from "@/styles/Home.module.scss";
import { Inter } from "next/font/google"; // Replace with actual font import if using

import bannerImg from "/public/assets/images/liberary-banner.png";
import BishopSign from "/public/assets/images/Bishop-sign.png";
import Features from "@/components/liberary/Features";
import Services from "@/components/liberary/Services";
import CommitteeList from "@/components/comman/CommitteeList";
import {
  LibraryAdvisoryCommeitteeTableData,
  LibraryAdvisoryCommeitteeTablehead,
  LibraryWorkingTableData,
  LibraryWorkingTablehead,
} from "@/config";
import SectionImage from "/public/assets/images/Director.jpg";
import Image from "next/image";
import PageContent from "@/components/comman/PageContent";

const inter = Inter({ subsets: ["latin"] }); // Example of font setup

const Director = () => {
  return (
    <>
      <Head>
        <title>Spips</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Banner
          bannerImg={bannerImg}
          heading="Director"
          description="Lorem ipsum dolor sit amet consectetur adipiscing eli mattis sit phasellus mollis sit aliquam sit nullam."
        />

        <Features
          sectionGap="both"
          SectionImage={SectionImage}
          descriptionClass="about_message"
          className="bg_white"
          content={
            <>
              About Father SHould be there
              <br />
              <h3 className="heading-5">LIFE PHILOSOPHY</h3>
              <br />
              “Inspire & aspire to create enabling environment that encourages
              everyone to explore their maximum potential, promotes self-esteem
              and inspires a life with dignity and knowledge”
            </>
          }
        />

        <PageContent
          sectionGap={"bottom"}
          className="bg_white"
          title={"EXPERIENCE"}
          description={
            <>
              Rev. Fr. Simon Raj has extensive experience of working with
              International Relief and Development Agencies and Consultancies
              focused on poverty alleviation in the state of Madhya Pradesh. He
              has been leading Indore Diocese Social Service Society for the
              past 8 years as its Director and has been managing operations of{" "}
              <strong className="small-text">
                25 parishes, 210 villages, 50 slums, 78 Panchayats in three
                districts at Indore, Dewas and Dhar of Catholic Diocese of
                Indore.
              </strong>{" "}
              Earlier, he has served as the Parish Priest and Development
              officer at Chotta Bangardha, Airport area, Indore from 2000 to
              2006.
              <br />
              <br />
              Highly acclaimed for his program quality management skills, he has
              worked in collaboration with Miserere Germany, World Vision India,
              Caritas India, Caritas Spain, MPSSS, Child Line, CNL, MI, CRS and
              many other renowned national and international organisations. He
              has spearheaded various development program plannings, monitoring
              and evaluation operations at different states in India like
              Orissa, Madhya Pradesh and Chattisgarh.
              <br />
              <br />
              Much loved and respected as a Youth and Vocations Director, Fr.
              Simon Raj has been working for the development and upliftment of
              Youth for 10 years now. During this tenure, he has also worked as
              a consultant with the Youth Rural Life Skill Development
              Foundation (YRLSDF), was the Program coordinator of the Asian
              youth Cross at regional Level in 2009 and served as a Program
              Manager at the National and Regional Youth Convention in Indore &
              Bhopal. Additionally, Fr. Simon Raj was nominated as a panel
              interviewer for CBCI CARD, Delhi and Caritas India Employee
              Selection.
              <br />
              <br />
              Apart from his vast area of expertise, he has also been working as
              Freelance Consultant for nine dioceses at Madhya Pradesh, he has
              headed various significant consulting reports on social
              development and growth management.
            </>
          }
        />
        <Features
          sectionGap="bottom"
          SectionImage={SectionImage}
          descriptionClass="about_message"
          leftImage={true}
          className="bg_white"
          title={"CORE SKILLS"}
          content={
            <>
              Rev. Fr. Simon Raj is an effective communicator with proven team
              building abilities. Trained in Competence Assessment, he is able
              to draw the best from the people he works with. A people’s leader
              he invests qualitatively in need-based capacity building of the
              human resources.
              <br />
              <br />
              Having strong analytical and evaluation skills he has led
              qualitative scientific and social research nationally and
              internationally and published reports, manuscripts in peer
              reviewed journals, presentations at meeting and conferences, etc
              <br />
              <br />
              Networking, linkages and advocacy is Rev. Fr. Simon Raj’s forte.
              He excels in Conflict Resolution and Peace Building. Adept in
              financial management he was provided technical assistance for
              execution of various project work as superior and an external
              consultant and has been well appreciated for his efforts.
            </>
          }
        />
       
        <PageContent className="bg_white" title="Remaining Sections " description={<><ul><li>ACADEMIC QUALIFICATION</li>
        
        <li>TRAINING & WORKSHOPS</li>
        <li>ACHIEVEMENTS</li>
        <li>CONTACT INFORMATION</li>
        </ul></>} />
       
        <div></div>
      </main>
    </>
  );
};

export default Director;
