import Banner from "@/components/banner";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import styles from "@/styles/Home.module.scss";
import { Inter } from "next/font/google"; // Replace with actual font import if using

import bannerImg from "/public/assets/images/college-banner.png";
import CommitteeList from "@/components/comman/CommitteeList";
import {
  LibraryAdvisoryCommeitteeTableData,
  LibraryAdvisoryCommeitteeTablehead,
  LibraryWorkingTableData,
  LibraryWorkingTablehead,
  managingCommittee,
  managingCommitteeDeatils,
} from "@/config";
import CommitteeTable from "@/components/comman/CommitteeList";
import PageContent from "@/components/comman/PageContent";



const Careers = () => {
    const [currentDomain, setCurrentDomain] = useState("");

    useEffect(() => {
      // Ensure we are in the client-side environment
      if (typeof window !== "undefined") {
        setCurrentDomain(window.location.hostname); // Get the current domain
      }
    }, []);
  return (
    <>
      <Head>
        <title>SPIPS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Banner
          bannerImg={bannerImg}
          heading="Careers"
          Contact={true}
          />
    
<PageContent
          sectionGap="both"
          className="bg_white"
          title="Work With Us"
          content={
            <>
            <div className="d-flex justify-content-center" >
            <iframe
        src={`https://docs.google.com/viewerng/viewer?url=${currentDomain}/assets/documents/JOb.pdf&embedded=true`}
        style={{ width: "640px", height: "800px" }}
        allowFullScreen
        title="Statutory Bodies PDF Viewer"
      />

      
            </div>
           
            </>
          }
        />
      </main>
    </>
  );
};

export default Careers;
