import Banner from '@/components/banner';
import Head from 'next/head';
import React from 'react';
import styles from "@/styles/Home.module.scss";
import { Inter } from 'next/font/google'; // Replace with actual font import if using

import bannerImg from "/public/assets/images/liberary-banner.png";
import SectionHeading from '@/components/comman/sectionHeading';
import PageContent from '@/components/comman/PageContent';


const inter = Inter({ subsets: ['latin'] }); // Example of font setup

const Library = () => {
  return (
    <>
      <Head>
        <title>Spips</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Banner bannerImg={bannerImg}  />
<PageContent sectionGap="both" />
        <div  >

        </div>
        
      </main>
    </>
  );
};

export default Library;
