import Banner from "@/components/banner";
import Head from "next/head";
import React from "react";
import styles from "@/styles/Home.module.scss";
import { Inter } from "next/font/google"; // Replace with actual font import if using

import bannerImg from "/public/assets/images/liberary-banner.png";
import SectionHeading from "@/components/comman/sectionHeading";
import PageContent from "@/components/comman/PageContent";
import Features from "@/components/liberary/Features";
import Services from "@/components/liberary/Services";
import CommitteeList from "@/components/comman/CommitteeList";
import { LibraryAdvisoryCommeitteeTableData, LibraryAdvisoryCommeitteeTablehead, LibraryWorkingTableData, LibraryWorkingTablehead, policy } from "@/config";
import ListingsSection from "@/components/comman/ListingsSection";

const inter = Inter({ subsets: ["latin"] }); // Example of font setup

const Policy = () => {
  return (
    <>
      <Head>
        <title>Spips</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <Banner bannerImg={bannerImg} heading="Policy" description="Lorem ipsum dolor sit amet consectetur adipiscing eli mattis sit phasellus mollis sit aliquam sit nullam."  />
       
        <ListingsSection
          sectionGap="both"
          title="Policy"
          listTitle="Policy"
          listData={policy}
          tablehead={LibraryAdvisoryCommeitteeTablehead} 
          tableData={LibraryAdvisoryCommeitteeTableData}
        />
        <div></div>
      </main>
    </>
  );
};

export default Policy;
