import Banner from "@/components/banner";
import Head from "next/head";
import React from "react";
import styles from "@/styles/Home.module.scss";
import { Inter } from "next/font/google"; // Replace with actual font import if using

import bannerImg from "/public/assets/images/liberary-banner.png";
import SectionHeading from "@/components/comman/sectionHeading";
import PageContent from "@/components/comman/PageContent";
import Features from "@/components/liberary/Features";
import Services from "@/components/liberary/Services";
import CommitteeList from "@/components/comman/CommitteeList";
import { LibraryAdvisoryCommeitteeTableData, LibraryAdvisoryCommeitteeTablehead, LibraryWorkingTableData, LibraryWorkingTablehead } from "@/config";
import SectionImage from "/public/assets/images/chairman.png";


const inter = Inter({ subsets: ["latin"] }); // Example of font setup

const Chairman = () => {
  return (
    <>
      <Head>
        <title>Spips</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <Banner bannerImg={bannerImg} heading="Chairman" description="Lorem ipsum dolor sit amet consectetur adipiscing eli mattis sit phasellus mollis sit aliquam sit nullam."  />
        <PageContent sectionGap="both" />
        <Features sectionGap="bottom" SectionImage={SectionImage} />
        <Services />
        <CommitteeList
          sectionGap="both"
          title="Library Advisory Committee"
          description={
            <>
              Lorem ipsum dolor sit amet consectetur adipiscing elidolor mattis
              sit
              <br /> phasellus mollis sit aliquam sit nullam neques.
            </>
          }
          tablehead={LibraryAdvisoryCommeitteeTablehead} 
          tableData={LibraryAdvisoryCommeitteeTableData}
        />
         <CommitteeList
          sectionGap="bottom"
          title="Meet our Library Staff"
          description={
            <>
              Lorem ipsum dolor sit amet consectetur adipiscing elidolor mattis
              sit
              <br /> phasellus mollis sit aliquam sit nullam neques.
            </>
          }
          tablehead={LibraryWorkingTablehead} 
          tableData={LibraryWorkingTableData}
        />
        <div></div>
      </main>
    </>
  );
};

export default Chairman;
